import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import ErrorAlert from "@/components/auth/ui/ErrorAlert";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
});


export const metadata: Metadata = {
  title: "AJK-PSC Official Website of Public Service Commission",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} font-poppins` }
      >
        <Providers>
          {children}
          <ErrorAlert />
        </Providers>
      </body>
    </html>
  );
}
