import type { Metadata } from "next";
import {  Inter } from "next/font/google"; // Fix import
import "./globals.css";
import { Providers } from "./providers";
import ErrorAlert from "@/components/auth/ui/ErrorAlert";

const inter = Inter({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin-ext"],
  variable: "--font-inter", // ✅ Enable variable support
});

export const metadata: Metadata = {
  title: "AJK-PSC Official Website of Public Service Commission",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <Providers>
          {children}
          <ErrorAlert />
        </Providers>
      </body>
    </html>
  );
}
